### ISSUE TITLE
爆弾の大きさ

### ISSUE THREAD

**Issue by c0a22091** [2tut/ProjExD_02#1]
https://github.com/2tut/ProjExD_02/blob/bca2ae4c8868e710584a372324385c811c5cd147/dodge_bomb.py#L78C13-L78C13
もう少し爆弾の大きくする速度を上げてもいいかも。。

**Comment by 2tut** [comment]
fixed in e34794b887ab360d45f752fad1d743301e88017e

**Comment by 2tut** [comment]
Fixed in e34794b887ab360d45f752fad1d743301e88017e
